#!/bin/sh

ORIG=$1
COPY=$2

echo "## `date`  begin"

find $ORIG -type f|cut -d "/" -f 2-|while read LINE
    do
	FILE=`/bin/basename $LINE`
	DIR=`/bin/dirname $LINE|sed "s/$/\//"|grep -v "^\./$"`
	OSUM=`sum $ORIG$LINE|cut -d " " -f 2` 
	CSUM=`sum $COPY$LINE|cut -d " " -f 2`
	if [ "$OSUM" != "$CSUM" ]
	then
		echo "$LINE differs $OSUM - $CSUM" >&2
#		mkdir -p $COPY$DIR
#		cp -rp $ORIG$DIR$FILE $COPY$DIR || echo $ORIG$LINE >> output.err
	fi
    done

echo "## `date` finished"
