#!/usr/bin/env bash

# Make sure we were not launched twice
[ -n "${BASH_HELPERS:-}" ] && echo "abort" && return || BASH_HELPERS=$(realpath "$BASH_SOURCE")

[ -n "${BASH_SOURCE[0]:-}" ] && [ "${BASH_SOURCE[0]}" = "$0" ] && {
	echo "$(basename "$0") is meant to be sourced, not run" >&2
	exit 1
}

PID=$$
PGM=${PGM:-$(basename "$0")}
BINDIR="$(cd $(dirname $BASH_SOURCE) && pwd)"
BASEDIR="${BASEDIR:-$(dirname "$BINDIR")}"
echo ":$PATH:" | grep -q ":$BINDIR:" || export PATH="$BINDIR:$PATH"

TMP=${TMP:-$(mktemp -t $PGM 2>/dev/null || mktemp -t $PGM.XXXXX 2>/dev/null || echo /tmp/$PGM.$$)}
LOCK=/tmp/$PGM.lock
trap 'rm -f $TMP.* $LOCK' EXIT

OPTS=${OPTS:-hqv}
LONGOPTS="${LONGOPTS:-help,quiet,verbose}"
SYNTAX="${SYNTAX:-$(echo $(
	echo $OPTS | sed "s/-://g" | sed "s/\(.*\)/[-\\1] [<args>]/g" | sed "s/\(.\):/] [-\\1 <value>/g"
	echo $LONGOPTS | sed "s/,/] [--/g; s/^/[--/; s/$/]/"
))}"

USAGE=${USAGE:-$PGM $SYNTAX}

DEBUG=${DEBUG:-}

RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
STD="\033[0m"

# Utility functions for true/false checking
is_true() {
	lower=$(echo "${1:-}" | tr "[:upper:]" "[:lower:]")
	case "$lower" in
	yes | y | on | true | 1) return 0 ;;
	*) return 1 ;;
	esac
}

is_false() {
	lower=$(echo "${1:-}" | tr "[:upper:]" "[:lower:]")
	case "$lower" in
	no | n | off | false | 0) return 0 ;;
	# "") return 0 ;;  # Empty is not false, it's null
	*) return 1 ;; # Unknown is false
	esac
}

# Debug checking function
debug_mode() {
	is_true "$DEBUG"
}

log() {
	[ -z "$1" ] && return
	local append err

	err=$(echo "$1" | grep -E "^[0-9]+$" || true)
	[ -z "$err" ] || shift

	case "$err" in
	0) COLOR=${GREEN} ;;
	"") COLOR=${YELLOW} ;;
	*)
		COLOR="$RED"
		append=" ($err)"
		;;
	esac

	[ "${1:-}" = "-n" ] && n="-n" && shift || n=
	[ -n "$*" ] || return
	printf "${COLOR}%s:${STD} %s\n" "$PGM" "$*${append:-}"
}

debug() {
	debug_mode && log "$*"
}

success() {
	log 0 "$@"
}

error() {
	local err=$(echo "$1" | grep -E "^[0-9]+$" || true)
	[ -z "$err" ] || shift
	[ ${err:-0} -ne 0 ] || err=1
	log ${err:-1} "$*"
}

end() {
	local caller_file="${BASH_SOURCE[1]}"
	local caller_line="${BASH_LINENO[0]}"
	# err=$(echo "$1" | grep -E "^[1-9][0-9]*$" || true)
	local err=$(echo "${1:-}" | grep -E "^[0-9]+$" && shift || false)
	[ -z "$err" ] || shift
	if [ "$err" -a "$err" != "0" ]; then
		prefix="[ERROR]"
		debug_mode && suffix="$caller_file:$caller_line" || suffix=
	else
		prefix=
		suffix=
	fi

	[ "${1:-}" = "-n" ] && n="-n" && shift || n=
	local message=${@:-$(debug_mode && echo Finished processing)}
	log $err $prefix "$message"
	[ -n "$suffix" ] && echo "  trace: $suffix"
	exit ${err:-0}
}

die() {
	local err=$(echo "$1" | grep -E "^[0-9]+$" || true)
	[ -z "$err" ] || shift
	[ ${err:-0} -ne 0 ] || err=1
	end $err "$@"
}

yesno() {
	default=n
	choice="y/N"
	[ "$1" = "y" ] && default=y && choice="Y/n" && shift
	[ "$1" = "-y" ] && default=y && choice="Y/n" && shift
	[ "$@" ] && message="$@" || message="Answer"
	message="$message ($choice) "
	read -u1 -p "$message" answer
	[ "$answer" = "" ] && answer=$default
	answer=$(echo "$answer" | tr "[:upper:]" "[:lower:]")
	[ "$answer" = "y" ] && return 0
	[ "$answer" = "yes" ] && return 0
	return 1
}

readvar() {
	for var in $@; do
		varname=$(echo $var | sed "s/\([a-z]\)\([A-Z]\)/\\1 \\2/g")
		if [ "$AUTOMATIC" = "yes" ]; then
			echo "$varname: ${!var}"
		else
			read -e -p "$varname: " -i "${!var}" $var
		fi
	done
}

get_config() {
	[ -z "${ENV_PATTERN:-}" ] && log 1 "$(system_message error_env_pattern_missing)" && return 1
	set | egrep "${ENV_PATTERN:-}" || log 1 "$(system_message error_empty_config)"
}

usage() {
	if [ ! "$USAGE" ]; then
		PAR=$(echo $OPTS | sed 's/.://g' | grep -v "^$" | sed "s/\([a-zA-Z0-9]*\)/[-\1]/g")
		PAROPT=$(echo $OPTS | sed "s/-://" | sed 's/\(.\)/\1\//g' |
			sed 's/\(.\)\/:\//[-\1 <value>] /g' |
			sed "s/.\///g")
		USAGE=$(echo $PGM $PAR $PAROPT "[...]" | sed "s/  / /g")
	fi
	echo "usage: $USAGE"
}

help() {
	[ -n "${HELP:-}" ] && echo "$HELP" || usage
}

detailed_help() {
	cat $BASEDIR/app/doc/help.txt
	end
}

[ -f "$BASEDIR/.env" ] || log "No .env, using defaults, copy $BASEDIR/.env.example as .env and edit adjust to your needs"
[ -f "$BASEDIR/.env" ] && source "$BASEDIR/.env" || true

if is_true "${OPTSINHELPER:-no}"; then
	# Parse common args, script-specific args are parsed in the script itself
	parsed_opts=$(getopt -o $OPTS -l "$LONGOPTS" -- "$@" 2>$TMP.getopt) || end $? "$USAGE $(
		echo
		sed "s/^getopt[\b:]*//" $TMP.getopt
	)"
	debug "parsed_opts $parsed_opts"
	for o; do
		case $o in
		-p | --path)
			printf '%s\n' "$o set to $2"
			shift 2
			;;
		-h | --help)
			help
			end
			;;
		-q | --quiet)
			STDOUT="/dev/null"
			QUIET=yes
			DEBUG=no
			shift
			;;
		-v | --verbose)
			STDERR="&1"
			DEBUG=yes
			shift
			;;
		--)
			shift
			break
			;;
		# (*) log 1 "option $1 not processed by helper $2";
		esac
	done
	# [ "$#" -eq 0 ] || debug "unprocessed args $@"

	[ ${ERROR:-} ] && end $ERROR "$(usage)
type '$PGM --help' for more info"
fi
