#!/bin/bash

# Définir les variables avec des chemins absolus
packages_folder=/home/magic/packages
PGM=$(basename $0)
BINDIR=$(realpath $(dirname $0))
BASEDIR=$(dirname $BINDIR)
cd $BASEDIR
TMP=$(mktemp /tmp/$PGM.XXXXXX)
CACHE=/tmp/$PGM.cache

# Ajouter les chemins nécessaires au PATH
export PATH=/opt/magic/bin:$BINDIR:$PATH

. $(which wp-helpers) || exit 1

# Preferences may override the defaults above (e.g. packages_folder)
for prefs in /etc/$PGM ~/etc/$PGM ~/.$PGM
do
    [ -f "$prefs" ] && . "$prefs"
done

date > $CACHE.beenthere

# Fonction de log
log() {
    local code=0
    if [[ $1 =~ ^[0-9]+$ ]]; then
        code=$1
        shift
    fi

    local color
    if [[ $code -eq 0 ]]; then
        color="\e[32m"  # vert
    else
        color="\e[31m"  # rouge
    fi
    echo -e "${color}$PGM\e[0m: $*" >&2
    echo -e "$*" >> $CACHE.beenthere
}

# Nettoyage temporaire à la fin du script
trap "rm -f $TMP*" 0 1 2 3 15

# Vérifier la présence de wp-sync-local-repo
wpsync=$(which wp-sync-local-repo)
[ "$wpsync" ] || { echo "wp-sync-local-repo not found in PATH"; exit 1; }

log "Getting the changes from the repository"
git pull >/dev/null && git push >/dev/null || exit $?

log "Get the list of hosted plugins"
$wpsync -l | sed "s:^:$BASEDIR/:" > $TMP.plugins.hosted
log "$(cat $TMP.plugins.hosted | wc -l) plugins hosted"

if [[ -f $CACHE.plugins.installed && $(find $CACHE.plugins.installed -mmin -60) ]] && grep -q "[a-z]" $CACHE.plugins.installed;
 then
    log "Using cached version of active plugins"
else
    log "Getting plugins currently installed"
    servers -y -c "/opt/magic/bin/list-local-websites -wp" | grep -v "#" | cut -f 2 | cut -d " " -f 1 > $CACHE.plugins.installed
    # log "Getting plugins currently active"
    # servers -y -c "/opt/magic/bin/list-local-websites -wp" | grep "[[:space:]]active[[:space:]]" > $CACHE.plugins.active
fi
log "$(cat $CACHE.plugins.installed | wc -l) plugins installed"

log "Get the list of plugins to manage"
for plugin in $(cat $CACHE.plugins.installed | sort -u)
do
    # log "Checking $plugin"
    grep "/$plugin " $TMP.plugins.hosted
done | sed "s/[()]//g" > $TMP.plugins.managed
log "$(cat $TMP.plugins.managed | wc -l) plugins to manage"

cat $TMP.plugins.managed | while read path version
do
    slug=$(basename $path .zip)
    echo "$slug $path $version"
done | sort -u | while read slug path version
do
    parent=$(dirname $path)
    package=$packages_folder/$slug.zip  
    if [ -f $package ]; then
        pkg_version=""
        main_file=$(unzip -l $package | awk '{print $NF}' | grep -E "^$slug/[^/]+\.php$" | while read file
        do
            if unzip -p $package $file | grep -q "Plugin Name:"; then
                echo $file
                break
            fi
        done)
        
        if [ "$main_file" = "" ]; then
            echo "No plugin info for $slug" >&2
        else
            pkg_version=$(unzip -p $package $main_file | grep "Version:" | head -1 | awk -F ':' '{print $2}' | xargs echo)
        fi
        
        if [ "$(compare_versions "$pkg_version" "$version")" != "<" ]; then
            # log "$slug up to date ($pkg_version >= $version)"
            continue
        fi
    fi
    log "Updating $slug to $version"
    cd $parent && zip -qr $TMP.zip $slug && mv $TMP.zip $package && log "$slug updated to $version" && echo "$slug updated to $version" >> $TMP.updated && continue
    err=$?
    log $err "Error $err updating $slug to $version"
    echo "Error $err updating $slug to $version" >> $TMP.errors
done

if [ -s $TMP.updated ]; then
    echo $(cat $TMP.updated | wc -l) plugins updated:
    cat $TMP.updated
fi
if [ -s $TMP.errors ]; then
    echo $(cat $TMP.errors | wc -l) errors updating plugins:
    cat $TMP.errors
fi
