#!/bin/sh

[ ! "$BASH" ] && echo "Should be launched from bash" && exit $?
. $(which helpers) || exit 1


wpcmd() {
	if [ "$user" = "$USER" ]
	then
		wp $@
		return $?
	fi
	# Check if $USER can sudo as $user
	if sudo -u $user wp $@
	then
		return $?
	else
		log 1 "Run as $user or as a user that can sudo as $user"
		return 1
	fi

	# [ "$EUID" -eq 0 ] \
	# 	&& su $user -c "wp $@" \
	# 	|| wp $@
	# 	return $?
}
wpfastconfig() {
	export table_prefix=$(grep '\$table_prefix' wp-config.php | cut -d "'" -f 2)
	for config in DB_NAME DB_USER DB_PASSWORD DB_HOST
	do
		# eval "$config='$(wpcmd config get $config)'"
		eval "$config='$(grep "define( *'$config'" wp-config.php | cut -d "'" -f 4 )'"
	done
	export DB_NAME DB_USER DB_PASSWORD DB_HOST
	[ ! "$DB_HOST" ] && DB_HOST=localhost
	export siteurl=$(echo "select option_value from ${table_prefix}options where option_name = 'siteurl';" \
	| mysql -BN -u $DB_USER -p"$DB_PASSWORD" -h $DB_HOST $DB_NAME)

}
webgettitle() {
	log webgettitle $@
	[ "$3" ] && default_title=$3
	if [ -d "$1" ]
	then
		path=$1
		url=$2
		(
 		[ -f "$path/index.php" ] && cat $path/index.php
		[ -f "$path/index.html" ] && cat $path/index.html
		)
	else
		url=$1
	fi  | tr "\n" " " | grep -i "<title[ >]" > $TMP.index
	if [ $? -eq 0 ]
	then
		log using local files
		cat $TMP.index
	elif [ "$url" ]
	then
		log trying the slow way
		echo $url | grep -q "https*://" || (log no url in $@; return -1)
		echo "not checked yet"
		redir=$(curl -is $url | grep "Location: http" | cut -d " " -f 2); [ "$redir" ] && log " redirected to $redir" && url=$redir
		log url $url
		curl -s --connect-timeout 10 "$url" || return 404
	fi | tr "\n" " " | grep -i "<title[ >]" > $TMP.index
	if [ $? -ne 0 ]
	then
		log still nothing found
		[ "$default_title" ] && echo "default_title $default_title" && return
		[ "$url" ] && echo "$url" | cut -d / -f 3 && return
		[ "$path" ] && echo "path $path" && return
	else
		log found $(cat $TMP.index | wc -l) lines
		cat $TMP.index
	fi | sed "s:.*<title.*>\([^<>]*\)</title>.*:\\1:i" | sed -e "s/&amp;//g" -e "s:<br/*>.*::i" > $TMP.title
	title=$(cat $TMP.title)
	# [ ! "$title" ] && $(curl -Ls --connect-timeout 10 "$url" | tr "\n" " " | grep -i "<title[ >]" | sed "s:.*<title.*>\([^<>]*\)</title>.*:\\1:i" | sed -e "s/&amp;//g" -e "s:<br/*>.*::i")
	[ ! "$title" ] && title=$(echo "$url" | cut -d / -f 3-) && log using url $title
	[ ! "$title" ] && log $url no title && echo $url && return -1
	[ "$title" = "301 Moved Permanently" ] && log $url $title && continue
	[ "$title" = "302 Found" ] && log $url $title && continue
	[ "$title" = "Website not configured" \
	-o "$title" = "Website under construction" \
	-o "$title" = "Website under maintenance" ] && title="$domain - $title"
	log " $title"
	while (echo "$title" | grep -q "&.*;")
	do
		recode=$(echo "$title" | sed "s/.*\(&[^;]*;\).*/\\1/")
		recoded=$(echo "$recode" | recode html..utf8)
		title=$(echo "$title" | sed "s/$recode/$recoded/")
		log " recoded to $title"
	done
	domain=$(echo "$url" | cut -d / -f 3)
	# title=$(echo "$title" | sed "s/AMPERSAND/&/g")
	# sub=$(echo "$domain" | cut -d "." -f 1)
	# [ "$sub" = "dev" -o "$sub" = "preview" ] && title="<sup>[$sub]</sup> $title"
	echo $title
}

wpgetname() {
	[ "$1" ] && path=$1 || path=$PWD
	(
	echo "$path" | grep -q "/plugins/" && grep "^[[:blank:]\*;]*Plugin Name:" "$path"/*.php \
	|| echo "$path" | grep -q "/themes/" && grep -l "^[[:blank:]\*;]*Theme Name:" "$path"/style.css 2>/dev/null \
	|| return $?
	) | sed -E "s/.*(Plugin|Theme) *Name: *//"
}

wpgetdesc() {
	[ "$1" ] && path=$1 || path=$PWD
	(
	echo "$path" | grep -q "/plugins/" && grep "^[[:blank:]\*;]*Description:" "$path"/*.php \
	|| echo "$path" | grep -q "/themes/" && grep -l "^[[:blank:]\*;]*Description:" "$path"/style.css 2>/dev/null \
	|| return $?
	) | sed -E "s/.*Description: *//"
}

wpgetversion() {
	p_version="^[[:blank:]\*;]*Version: *"
	p_number="[0-9]+(\.[0-9]+)*(-[0-9a-zA-Z]+)*"
	[ "$1" -a -d $(realpath "$1") ] && path="$1" \
	|| ( [ "$1" -a -f $(realpath "$1") ] && file="$1" ) \
	|| ( [ ! "$1" ] && path=$PWD ) || return $?
	# log path $path
	if [ "$path" -a ! "$file" ]
	then
		(
		echo "$path" | grep -q "/plugins/" && grep -l "^[[:blank:]\*;]*Plugin Name:" "$path"/*.php  \
		|| echo "$path" | grep -q "/themes/" && grep -l "^[[:blank:]\*;]*Theme Name:" "$path"/style.css 2>/dev/null \
		|| return $?
		) \
		| xargs grep -l  "$p_version" >$TMP.mainphp 2>/dev/null
		file=$(head -1 $TMP.mainphp)
	fi
	# log file $file
	if [ "$file" ]
	then
		cat "$file" \
		| tr "[[:blank:]]" " " \
		| grep -E "$p_version$p_number" \
		| grep -Eo "$p_number" \
		| head -1 \
		| grep "[0-9]" \
		&& return
	fi
	return 1
}

prerelease_string_to_int()
{
	case $1 in
		rc)
		echo -1
		;;

		beta)
		echo -2
		;;

		alpha)
		echo -3
		;;

		dev)
		echo -4
		;;

		*)
		echo $1
	esac
}

compare_versions()
{
	[ "$1" = "$2" ] && return
	local v1=( $(echo "$1" | tr '.-' '  ') )
	local v2=( $(echo "$2" | tr '.-' '  ') )
	[ "${#v1[*]}" -gt "${#v2[*]}" ] && len="${#v1[*]}" || len="${#v2[*]}"
	for ((i=0; i<len; i++))
	do
		n1=$(prerelease_string_to_int "${v1[i]:-0}")
		n2=$(prerelease_string_to_int "${v2[i]:-0}")

		[ $n1 -gt $n2 ] && echo ">" && return 1
		[ $n1 -lt $n2 ] && echo "<" && return -1
	done
	echo "=" && return 0
}

increment_version() {
	[ "$2" ] && level=$1 && v=$2 || v=$(echo $1 | cut -d "-" -f 1)
	echo "$1" | grep -q -E "^[0-9]+\.[0-9][0-9\.]*" && v=$1 && level=$2 \
	|| ( echo "$2" | grep -q -E "^[0-9]+\.[0-9][0-9\.]*" && v=$2 && level=$1 ) \
	|| return $?
	M=$(echo $v | cut -d . -f 1 | grep -E "^[0-9]+$" || echo 0)
	m=$(echo $v | cut -d . -f 2 | grep -E "^[0-9]+$" || echo 0)
	p=$(echo $v | cut -d . -f 3 | grep -E "^[0-9]+$" || echo 0)

	case $level in
		"major")
		M=$(($M + 1)) && m=0 && p=
		;;
		"minor")
		m=$(($m + 1)) && p=
		;;

		*)
		p=$(($p + 1))
	esac
	echo $M.$m.$p | sed "s/\.*$//"
}
